name: Pylint

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint NBT python-dotenv requests
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=6 --disable=no-self-argument,similarities,invalid-name $(git ls-files '*.py')
